### ISSUE TITLE
Set-Up Issue

### ISSUE THREAD

**Issue by tombaer1044** [maartentamboer/X-Touch-Mini-FS2020#10]
Dear Maarten, 
at first many thanks for your effort! Really appreciate your project. 

However, I only got this far:  

- The command window remains open (thanks to your tip with the command prompt) 
- The command window recognizes the airplane and shows "Loading config file: Configurations/config_default.json" 
- The command window recognizes the Xtouch and shows the individual inputs as "on_cc_data:" with the respective No. behind

And this is where the issue starts. I can twist and turn the knobs, but nothing seems to happen in the plane ... I re-installed the simconnect and even the current sdk... 

Am I overlooking a step in the installment? 

Thanks again for your efforts! 
Best, 
Thomas

**Comment by maartentamboer** [comment]
Hi Thomas,

I've got a couple of questions for troubleshooting

Did you set your encoders to the relative2 mode in the x-touch editor? See https://github.com/maartentamboer/X-Touch-Mini-FS2020#x-touch-configuration for more information.

Are the buttons working?

Do the lights of the buttons turn on when you enable let's say the FD or AP in the simulator itself?

**Comment by maartentamboer** [comment]
Closed due to inactivity
