### ISSUE TITLE
LED not working

### ISSUE THREAD

**Issue by cupax1000** [maartentamboer/X-Touch-Mini-FS2020#119]
Hello.

I've uploaded your profiles to my X Touch Mini, and while the encoders and buttons work fine, the LEDs don't.
They light up only while the buttons are pressed, but when I release them they turn off. So there is no feedback if the button (on the cockpit) is engaged or not.
Also, for example: if you press a button (let's say engage the AP) with a mouse on the cockpit, the assigned button's LED on the X Touch should turn ON, right? Well, it doesn't.

**Comment by dpakman** [comment]
I have the exact same problem.

**Comment by maartentamboer** [comment]
To me that sounds like the midi out is not working. 
1. Do you have any other MIDI devices connected to your PC? 
2. Can you sent the output of the application when you start it up? It should print the MIDI devices: https://github.com/maartentamboer/X-Touch-Mini-FS2020/blob/main/midiconnection.py#L7-L8

**Comment by cupax1000** [comment]
Hello.
This has been fixed. The problem was, that the global channel of X Touch Mini was set to 2. As soon as you change it to 1 the LEDs start working fine.
