### ISSUE TITLE
Another setup question

### ISSUE THREAD

**Issue by Noncon-229** [maartentamboer/X-Touch-Mini-FS2020#12]
I set the Min Value encoders in the x-touch editor to Relative 2.

Then ran X-Touch-Mini-FS2020.exe, a black window opens momentarily, and nothing else. 

The x-touch device is seen in device manager, and all the buttons light up. See that another user had a problem with possible conflicting USB input devices.  I removed all mine, on the keyboard/mouse/xtouch using the usb slots. 

Any thoughts?

**Comment by maartentamboer** [comment]
Can you open a command prompt and run the application in that? That should give a little more debug information related to your issue

**Comment by Noncon-229** [comment]
See attached picture.

After a search on "openport: error creating windows mm midi output port" results were mixed. It might be caused by another one of my devices using the midi port, or an issue with Windows 10 and how it assigns ports.  
[https://imgur.com/MLQYYMc](url)

Thanks for the response!

**Comment by Noncon-229** [comment]
Made some progress.  I think my usb headset was interfering with something, here is where I'm at now. 

1. Open X-Touch Editor
2. Loaded a saved .bin with Relative 2 settings
3. Closed Editor
4. Start FS2020 to Welcome Screen
5. Ran X-Touch-Mini-FS2020.exe
6. Black windows opens with the following:

Current aircraft: b'Cessna CJ4 Citation Asobo'
Loading config file: Configurations/config_default.json

7. Open Controls screen (in FS2020), no additional controller found

Should I see another controller?

**Comment by maartentamboer** [comment]
This tool interfaces directly with the API msfs, so you will not see a controller in the settings screen. If the application starts up an doesn't close it should work

**Comment by maclor** [comment]
Hi Guys,
I've the same issue. Definitely, this issue is related to the other audio-hardware working with usb. I've an external music card with a headset (Creative Sound Blaster Tactic3D Rage Wireless) and I've receiver an analogical issue. If I'll have time then I'll try to debug it.
Merry Xmass!

**Comment by maartentamboer** [comment]
See also https://github.com/maartentamboer/X-Touch-Mini-FS2020/issues/19 

I plan to make the midi device selectable through the config file

**Comment by maartentamboer** [comment]
https://github.com/maartentamboer/X-Touch-Mini-FS2020/pull/22

**Comment by maartentamboer** [comment]
Fixed in the latest release https://github.com/maartentamboer/X-Touch-Mini-FS2020/releases/tag/v1.1.0
