### ISSUE TITLE
Rotary Knob 6 plus 8 / Layer A create Errors in Console

### ISSUE THREAD

**Issue by reimuell** [maartentamboer/X-Touch-Mini-FS2020#13]
Hello,
I'm using your X-Touch Layout , I checked all rotary Encoder buttons in the X Touch Editor, They are all identical.
Pushing knob 6 and 8 - but only in layer A - create following messages
traceback (most recent call last):
  File "site-packages\mido\backends\rtmidi.py", line 171, in _callback_wrapper
  File "main.py", line 40, in handle_message
  File "rotaryencoder.py", line 91, in on_cc_data
  File "eventqueue.py", line 37, in __call__
  File "eventqueue.py", line 27, in __call__
TypeError: 'NoneType' object is not callable
on_cc_data: 6: 65
The error occurs when I tunr Button 6/Layera to the left or right, push brings no error. Unpressing Button 8 also (Button 8 turn left/right is possible, push also)
I

Is there a relativ easy way to debug this code without running FS2020. I'm ot a python export but I have programming knowledge on other languages.

**Comment by reimuell** [comment]
Further Investigations:
I believe this is not a problem of X-touch. If I change buttons (the coding) the error moves. The error comes up when using FLAPS_INC/FLAPS_DEC on a rotary button , and AP_PANEL_VS_HOLD ---> press a knob)

**Comment by maartentamboer** [comment]
The events that you use must be available in the underlying python-simconnect API. You can view a full list here:
https://github.com/odwdinc/Python-SimConnect/blob/master/SimConnect/EventList.py

Can you try `FLAPS_INCR` / `FLAPS_DECR` and `AP_VS_HOLD`

**Comment by maartentamboer** [comment]
Closed due to inactivity
