### ISSUE TITLE
Knob rotating speed

### ISSUE THREAD

**Issue by jFly123** [maartentamboer/X-Touch-Mini-FS2020#26]
Hi,

Is it possible to modify how fast values change when you rotate a knob? If I try to set baro minimums for some planes, the values jump from tens to thousands and it's difficult to set exact value quickly.

Is it possible for example to set this in config file for each knob separately?

Otherwise, thanks for great job. It's working nice!

**Comment by maartentamboer** [comment]
Can you check if your encoders are in relative2 mode in the x-touch editor software? https://github.com/maartentamboer/X-Touch-Mini-FS2020#x-touch-configuration

**Comment by jFly123** [comment]
Yes they are.

**Comment by maartentamboer** [comment]
What is the software printing when you rotate the encoder?
1 (incrementing or decrementing numbers):
```
on_cc_data: 1: 0
on_cc_data: 1: 1
on_cc_data: 1: 3
on_cc_data: 1: 4
on_cc_data: 1: 5
on_cc_data: 1: 6
on_cc_data: 1: 7
on_cc_data: 1: 8
```

or 2 (numbers between 60 and 70):
```
on_cc_data: 1: 61
on_cc_data: 1: 62
on_cc_data: 1: 65
on_cc_data: 1: 67
on_cc_data: 1: 67
```

**Comment by maartentamboer** [comment]
If you see 1, that means that the encoders are not in the correct mode. And you may have forgotten to press the `To Hardware` `Dump A` button in the x-touch editor global tab after modifying to relative2. The behavior that I see in the sim really matches with the issue you're describing when I put my encoders in the default state.

If you see 2 everything should work as expected, slowly turning the knob are small increments, fast turns are accelerated by FS itself.

If you see anything else, please attach a screenshot or the log from the application and which config you're using.

**Comment by jFly123** [comment]
If I make "normal" encoder turn I get values:
on_cc_data: 7: 65
on_cc_data: 7: 67
on_cc_data: 7: 67
on_cc_data: 7: 67
on_cc_data: 7: 67
on_cc_data: 7: 67
... and during the turn CJ4 baro mins goes from 0 to 14000.

If I keep longer delay between one step of turn, I get 10 increment in baro mins and software values are all 65.

If the problem is at msfs's end, do you think there's something that could be done?

**Comment by maartentamboer** [comment]
Which event are you sending (send the snippet of the config file)?

**Comment by jFly123** [comment]
`{
        "index": 7,
        "event_up": { "event": "Mobiflight.Generic_Upr_DATA_INC", "type": "manual", "value": 1 },
        "event_down": { "event": "Mobiflight.Generic_Upr_DATA_DEC", "type": "manual", "value": 1 }
    },  `

**Comment by jFly123** [comment]
I noticed today that usually when I run the software and turn encoder by one step, I get values 65 up and 63 down. Occasionally after running the software the value for one step is more like 61. When it's 61, heading bug and alt selector works very well. When it's 65, hgd and alt selectors go wild and change values very fast...I couldn't figure out why it sometimes gives different values for one step..

**Comment by maartentamboer** [comment]
That's strange. Generally when you rotate the encoder a single position it should indeed send 63 and 65. If you rotate very fast it will send lower and higher values because the encoder ticks happen faster then the midi messages. 
So if you see 66 it means that you rotated very fast and 2 ticks were combined in a single message.

The software calls the event n times. So for 65 it will call the up event 1 time. For 66 the event will be called 2 times.
https://github.com/maartentamboer/X-Touch-Mini-FS2020/blob/main/rotaryencoder.py#L92

**Comment by jFly123** [comment]
I did some more testing and the troublemaker seems to be Honeycomb Alpha. Everything's working fine when it's disconnected.

**Comment by maartentamboer** [comment]
WU4 has fixed the increment bug https://forums.flightsimulator.com/t/heading-increment-bug-10-degree-instead-of-1-explained/290173/609
