### ISSUE TITLE
Encoder led status not synced when switching between layers

### ISSUE THREAD

**Issue by Narvik-Ramius** [maartentamboer/X-Touch-Mini-FS2020#29]
Hi,
Many thanks for the latest release, with great improvements. 

I noticed than, when switching between layers, the LED status of the encoder don't re-sync.
For example : i use AP controls on Layer A, and now I've set up the encoders so that they light up when activating AP controls.
I use Layer B for garmin encoder and keys - thanks to mobiflight wasm module - which works great. But when switching back from LAyer B to layer A, the encoders leds are out of sync.

**Comment by maartentamboer** [comment]
This is kind of fixed. The main problem is that when you change the layer no midi event is send to identify that that happened. So I have to wait until the user presses a button or rotates a knob before I know that the layer has been changed.

But when I detect a layer change by the user the LEDs will be updated accordingly

**Comment by maartentamboer** [comment]
Fixed in https://github.com/maartentamboer/X-Touch-Mini-FS2020/releases/tag/v1.2.0
