### ISSUE TITLE
Layer B Encoder press # are incorrect

### ISSUE THREAD

**Issue by fherb007** [maartentamboer/X-Touch-Mini-FS2020#31]
On layer B

encoder 1 press = ENC 10
encoder 2 press = ENC 11
etc
encoder 7 press = ENC 16
encoder 8 press does not have a number

Correction:

encoder 1 press should = 9

Love this program so far, works a treat (except above...)
Thanks for your efforts.

**Comment by maartentamboer** [comment]
Sounds like a typical off by one error. Will look into this, this weekend

**Comment by maartentamboer** [comment]
https://github.com/maartentamboer/X-Touch-Mini-FS2020/commit/14529f55323b1760b1393f39cd3bd751aa79c314

**Comment by maartentamboer** [comment]
Fixed in https://github.com/maartentamboer/X-Touch-Mini-FS2020/releases/tag/v1.2.0

**Comment by fherb007** [comment]
All good now. Thanks Maarten
