### ISSUE TITLE
ADF 1, 10 & 100 on a single rotary swtich?

### ISSUE THREAD

**Issue by BigDinowski** [maartentamboer/X-Touch-Mini-FS2020#35]
Hi,

I wonder if it would be possible to set ADF 1, 10 & 100 KHz to a single rotary switch? Something like this:

	{
      "index": 6,
	  "description": "ADF Settings",
      "event_up": "ADF_100_INC",
      "event_down": "ADF_100_DEC",
      "alternate_event_up": "ADF_10_INC",
      "alternate_event_down": "ADF_10_DEC",
      "alternate2_event_up": "ADF_1_INC",
      "alternate2_event_down": "ADF_1_DEC",
      "event_short_press": "{alternate}",
      "event_long_press": "{alternate2}"
    },

**Comment by maartentamboer** [comment]
this might be possible by using conditions with global variables. Using that method we can also control the LED ring so you can easily see which mode you're in.
https://github.com/maartentamboer/X-Touch-Mini-FS2020/issues/14#issuecomment-774478934 Contains an example how to control a global variable. This is fairly complicated to use. So I will make an example for you later this week.

**Comment by BigDinowski** [comment]
Thank you very much! The LED ring method would also be useful, well, frankly for everything. COM WHOLE/FRAC, NAV WHOLE/FRAC, Garming Big/Small knob, etc.

**Comment by maartentamboer** [comment]
This is the config for an encoder that switches between 1, 10 and 100 and indicates in the LED ring which state it is in. Left led for 1, center led for 10, right led for 100.
```json
    {
      "index": 7,
      "event_up": {
        "type": "condition",
        "event": [ "{% if data.get_global_variable('ADF_SELECTION') == 100 %}",
                     "{{ data.trigger_event('ADF_100_INC', 1) }}",
                   "{% elif data.get_global_variable('ADF_SELECTION') == 10 %}",
                     "{{ data.trigger_event('ADF_10_INC', 1) }}",
                   "{% else %}",
                     "{{ data.trigger_event('ADF_1_INC', 1) }}",
                   "{% endif %}" ]
      },
      "event_down": {
        "type": "condition",
        "event": [ "{% if data.get_global_variable('ADF_SELECTION') == 100 %}",
                     "{{ data.trigger_event('ADF_100_DEC', 1) }}",
                   "{% elif data.get_global_variable('ADF_SELECTION') == 10 %}",
                     "{{ data.trigger_event('ADF_10_DEC', 1) }}",
                   "{% else %}",
                     "{{ data.trigger_event('ADF_1_DEC', 1) }}",
                   "{% endif %}" ]
      },
      "event_press": {
        "type": "condition",
        "event": [ "{% if data.get_global_variable('ADF_SELECTION') == 1 %}",
                     "{{ data.print('ADF_SELECTION 10') }}",
                     "{{ data.set_global_variable('ADF_SELECTION', 10) }}",
                     "{{ data.set_encoder_led_value(7, 7) }}",
                   "{% elif data.get_global_variable('ADF_SELECTION') == 10 %}",
                     "{{ data.print('ADF_SELECTION 100') }}",
                     "{{ data.set_global_variable('ADF_SELECTION', 100) }}",
                     "{{ data.set_encoder_led_value(7, 13) }}",
                   "{% else %}",
                     "{{ data.print('ADF_SELECTION 1') }}",
                     "{{ data.set_global_variable('ADF_SELECTION', 1) }}",
                     "{{ data.set_encoder_led_value(7, 1) }}",
                   "{% endif %}" ],
        "description": "Change ADF mode to a different setting"
      }
    }
```

I've also added this example to the config_default: https://github.com/maartentamboer/X-Touch-Mini-FS2020/blob/main/Configurations/config_default.json#L59

**Comment by maartentamboer** [comment]
Config example has been added to the release 1.2.1 https://github.com/maartentamboer/X-Touch-Mini-FS2020/releases/tag/v1.2.1
