### ISSUE TITLE
Lights on layer 2 are one off

### ISSUE THREAD

**Issue by SQLSammy** [maartentamboer/X-Touch-Mini-FS2020#37]
Hi,

when i use this
    {
      "index": 20,
      "event_press": [
        {
          "event": "TOGGLE_BEACON_LIGHTS",
          "type": "manual",
          "value": 0
        }
      ],
      "simvar_led": "LIGHT_BEACON"
    }

f.e. Button 4 on layer B will switch the Beacon, but Button 5 will light.

I think the lights on layer 2 position are one off

Regards
Andreas

**Comment by maartentamboer** [comment]
Fixed in https://github.com/maartentamboer/X-Touch-Mini-FS2020/releases/tag/v1.3.1
