### ISSUE TITLE
Improvement ideas

### ISSUE THREAD

**Issue by viboux** [maartentamboer/X-Touch-Mini-FS2020#4]
So glad I found your project. Everything I have hoped for. I was reading some solutions to make the X Touch Mini work with MSFS 2020 and was not satisfied with these solutions with tons of sketchy software (FreePIE + script + vJoy + mapping in MSFS2020). Your solution is the best, backed by a great Python SimConnect project.

I have made a few improvements yesterday to your code to support manual events which requires a specific value set for example the A32NX Managed and Selected modes in the AP (https://github.com/odwdinc/Python-SimConnect/issues/57).

> 

```
    {
      "index": 4,
      "event_up": "AP_ALT_VAR_INC",
      "event_down": "AP_ALT_VAR_DEC",
      "event_press": {"event": "ALTITUDE_SLOT_INDEX_SET", "type": "manual", "value": 1, "description": "A32NX - set AP Altitude Hold to selected mode"},
      "event_long_press": {"event": "ALTITUDE_SLOT_INDEX_SET", "type": "manual", "value": 2, "description": "A32NX - set AP Altitude Hold to managed mode"}
    },
```

Or to support multiple events for a single press.
```
  "buttons": [
    {
      "index": 1,
      "event_press": ["TOGGLE_FLIGHT_DIRECTOR", "AP_MASTER"],
      "simvar_led": "AUTOPILOT_FLIGHT_DIRECTOR_ACTIVE"
    },
```

Other ideas not yet implemented:

- conditional events based on a value (a bit like your triggers)
- plane specific configuration (G1000 planes, A32NX, 787) based on the currently selected plane
- UI to display the currently loaded configuration

Would love to contribute to the project, let me know if you want me to share the improvements to the code.

**Comment by maartentamboer** [comment]
Hey,
Nice to see that more people are finding my project and liking it 😄.
Any contributions are very welcome, so feel free to share your changes through a Pull request.

Conditional events is based on a value is definitely on my list. I hope to expand triggers with more functionality by allowing the user to test for specific values and so on. I'm looking into using jinja 2 https://jinja.palletsprojects.com/en/2.11.x/templates/#tests so the user could potentially add a rule in the json like this 
```json
"rule": "{% if simvarname is lt 10 %}"
```

Will probably work on that this weekend

**Comment by maartentamboer** [comment]
Good news, in version 1.0.0 there is now support for `conditional events` and `plane specific configurations`
Therfore i will now close this issue
