### ISSUE TITLE
Simple question :D

### ISSUE THREAD

**Issue by mrctll** [maartentamboer/X-Touch-Mini-FS2020#40]
This program is amazing and I'm starting to learn. How can I make the LED of the button light up with the function I enter?

Example having set the parking brake, I would like it to light up when I press it.

Thanks for your patience. : D

**Comment by maartentamboer** [comment]
A button entry consists of 2 parts. An event that is sent when you press the button, and a simvar that is monitored to light up the button. This way your LED is always in sync with the simulator.
An easy list of events and simvars can be found in the underlying library that I use, or in the MSFS SDK documentation.
Events: https://github.com/odwdinc/Python-SimConnect/blob/master/SimConnect/EventList.py
Simvars: https://github.com/odwdinc/Python-SimConnect/blob/master/SimConnect/RequestList.py

With those 2 resources you can create the following entry:
```json
{
    "index": 9,
    "event_press": "PARKING_BRAKES",
    "simvar_led": "BRAKE_PARKING_POSITION"
},
```
There is also a BRAKE_PARKING_INDICATOR simvar so you might have to try which one works

If this doesn't work, feel free to open another issue and I'll look into your use case with some more detail

**Comment by mrctll** [comment]
Thank you so much. your app is absolutely great and should be placed in flightsim.to. If everyone knew her, behringer would open a division for flight simulators.
