### ISSUE TITLE
CRJ - Throttle via vjoy

### ISSUE THREAD

**Issue by moguay** [maartentamboer/X-Touch-Mini-FS2020#43]
Hi, any possibility to integrate the management of the throttle slide with vjoy to be used it with the new CRJ plane ?

**Comment by SQLSammy** [comment]
I think you are at the wrong github, this is not for vJoy.

Here is the github for a tool to use the Behringer X-Touch mini with MSFS2020

**Comment by maartentamboer** [comment]
If you want to control the throttle with the fader on the x-touch you can set-up the following configuration in the fader section of the config files:
```json
"faders": [
    {
      "index": 1,
      "event_change": "THROTTLE_SET",
      "min_value": 0,
      "max_value": 16383
    }
  ],
```

if you have any other questions feel free to open another issue

**Comment by moguay** [comment]
Thanks for the reply, they is a misunderstanding seems to be.
I use x-touch with this software dev because it is very flexible and effective due to direct management by Simconnect api.

But asobo as help to dev a new CRJ, and I contacted them on this same subject. 
Because this new type of command management does not allow to use the API to manage the axle controls of the aircraft. So X-Touch-Mini-FS2020 i now incompatible with new aircraft management.

Asobo's response and aircraft developers is that the axes management system must go through a joystick axis management. 
is it is not intended to make it completely compatible with the API.

I can confirm that if you handle this via a virtual joystick vjoy, on the one hand, it's possible with MIDI controllers and that it works. Like can do FreePIE.

The only thing they were able to tell us to try to work around this problem is to try to use another event. But it does not work according to my first tries.

What he said to try: 
> You can try key_throttle_axis_set_ex1, key_throttle1_axis_set_ex1 and key_throttle2_axis_set_ex1
> However, this is not officially supported by US, so if it works, good for you. If not, we can't help. "
