### ISSUE TITLE
CRJ - Throttle via vjoy

### ISSUE THREAD

**Issue by moguay** [maartentamboer/X-Touch-Mini-FS2020#45]
Thanks for the reply but is closed quick, so i post again: 

Hi, any possibility to integrate the management of the throttle slide with vjoy to be used it with the new CRJ plane ?

They is a misunderstanding seems to be.
I use x-touch with this software dev because it is very flexible and effective due to direct management by Simconnect api.

But asobo as help to dev a new CRJ, and I contacted them on this same subject.
Because this new type of command management does not allow to use the API to manage the axle controls of the aircraft. So X-Touch-Mini-FS2020 i now incompatible with new aircraft management.

Asobo's response and aircraft developers is that the axes management system must go through a joystick axis management.
is it is not intended to make it completely compatible with the API.

I can confirm that if you handle this via a virtual joystick vjoy, on the one hand, it's possible with MIDI controllers and that it works. Like can do FreePIE.

The only thing they were able to tell us to try to work around this problem is to try to use another event. But it does not work according to my first tries.

What he said to try:

> You can try key_throttle_axis_set_ex1, key_throttle1_axis_set_ex1 and key_throttle2_axis_set_ex1
> However, this is not officially supported by US, so if it works, good for you. If not, we can't help. "

**Comment by maartentamboer** [comment]
Would it be possible to open the midi device twice? Then you can leave the fader configuration empty in my application and use something else to create a virtual joystick for the throttle control

**Comment by moguay** [comment]
No is not possible to open the midi device twice, i have try it

**Comment by maartentamboer** [comment]
My initial guess would be to search something like a midi splitter that works with a virtual cable to route the signals to different applications. 
![image](https://user-images.githubusercontent.com/1395437/111666031-9c1f8680-8813-11eb-932f-f5a37364cc67.png)

Looks like MIDIOX and loopMIDI together might be able to do it. But I have not tested these applications. https://www.tobias-erichsen.de/software/loopmidi.html
http://www.midiox.com/
https://www.youtube.com/watch?v=_QqlmD-uWG4&ab_channel=MysteryIslandsMusic

**Comment by moguay** [comment]
I have not try this. Some use a specific var change for CRJ ? Have you an idea to manage this var ?

LVAR:ASCRJ_FCP_ALT_SEL" Value="10" ValueOperation="Increment" />
LVAR:ASCRJ_FCP_ALT_CHANGE" Value="1" ValueOperation="Set">

LVAR's for knob turn and alt modifier.

**Comment by moguay** [comment]
For throttle have found this 2 var ASCRJ_Throttle_Lever_1 & ASCRJ_Throttle_Lever_2 in the CRJ700_Interior.xml file

**Comment by maartentamboer** [comment]
There is a seperate issue about lvars https://github.com/maartentamboer/X-Touch-Mini-FS2020/issues/39 and it appears that by using the mobiflight wasm module it is possible to access those.
