### ISSUE TITLE
Auto Switch Layer B to A when inactive

### ISSUE THREAD

**Issue by SQLSammy** [maartentamboer/X-Touch-Mini-FS2020#52]
Hi,

is it possible to add an option to revert from Layer B to A after some time of inactivity?

I would like to use Layer B for light and maybe views,
but most time i want to use layer 1 for flight/ap controls

Andreas

**Comment by maartentamboer** [comment]
I just looked in the manual of the x-touch and it is indeed possible to switch to a different layer by sending a `Program Change` midi message. I think I can make this a setting in the global config file where you specify a timeout after which it will automatically return to layer A

**Comment by maartentamboer** [comment]
This has been released in https://github.com/maartentamboer/X-Touch-Mini-FS2020/releases/tag/v1.5.0
An example can be found in https://github.com/maartentamboer/X-Touch-Mini-FS2020/blob/main/Configurations/config.json#L24
Documentation will be updated later
