### ISSUE TITLE
Mobiflight events

### ISSUE THREAD

**Issue by reimuell** [maartentamboer/X-Touch-Mini-FS2020#53]
Hello,

I need some help.
Not a single mobiflight G1000 command is working. I tried different , many. Any change to monitor, track this.
Steps I have done.
X touch softwaree 1.0.3 downloaded.
Mobiflight downloaded, Beta flagged, Module copied to community folder (checked: it's really there), Mobiflight is running too.

Starting x-touch-mini-fs2020, running , selected the correct config file with mobiflight commands, correct button is recognized (I see this in the console).

Nothing happens on/with the G1000 (Cessna). i tried directto button and different other buttons.
Any idea , hint.

I'm using visual studio to change the config files. While coding events I get syntax proposals. All mobiflight events are not visible. ? Because Mobiflight ist unknown to the visual studio environment? Correct?

**Comment by SQLSammy** [comment]
Post the code part where you config the mobiflight event

You don't need mobiflight running when you use this tool, you just need the module in community folder

**Comment by reimuell** [comment]
Hello meanwhile using the config file with mobiflight events x touch doesn't start anymore. Log windows apears for one second, can't read the message it's too fast, then stops. If I remove this coding parts exe runs errorfree again.
Visual studio still says these events are unknown and marks them as error.
Buttons:
{
      "index": 12,
             "event_up":  "MobiFlight.AS1000_MFD_FMS_Upper_INC", 
             "event_down": "MobiFlight.AS1000_MFD_FMS_Upper_DEC"

    },
    {
      "Index": 13,
      "event_up": { "event": "MobiFlight.AS1000_MFD_FMS_Lower_INC", "type": "manual", "value": 1 },
       "event_down": { "event": "MobiFlight.AS1000_MFD_FMS_Lower_DEC", "type": "manual", "value": 1 }
             
    }
knob:
{
      "Index": 20,
      "event_press": "MobiFlight.AS1000_MFD_DIRECTTO"
             
    }

I tried the rotary knob events also in simplified form without type and value. From my point of view these events have no value to pass.

**Comment by maartentamboer** [comment]
If the windows closes immediately try opening a command prompt and then running the application in that. That way it should keep the output visible

**Comment by reimuell** [comment]
This are th error messages ; appear only with the G1000 mobiflight commands include.
idi input devices: ['X-TOUCH MINI 0']
Midi output devices: ['Microsoft GS Wavetable Synth 0', 'X-TOUCH MINI 1']
Using midi input device: X-TOUCH MINI 0
Using midi output device: X-TOUCH MINI 1
Current aircraft: b'Cessna Skyhawk G1000 Asobo'
Loading config file: Configurations/config_baron_MOBI.json
WARNING: Event G1000_MFD_PAGE_KNOB_INC, was not found in simconnect list. Using a manual binding
WARNING: Event G1000_MFD_PAGE_KNOB_INC, was not found in simconnect list. Using a manual binding
WARNING: Event G1000_MFD_GROUP_KNOB_INC, was not found in simconnect list. Using a manual binding
WARNING: Event G1000_MFD_GROUP_KNOB_INC, was not found in simconnect list. Using a manual binding
WARNING: Event MobiFlight.AS1000_MFD_FMS_Upper_INC, was not found in simconnect list. Using a manual binding
WARNING: Event MobiFlight.AS1000_MFD_FMS_Upper_DEC, was not found in simconnect list. Using a manual binding
Traceback (most recent call last):
  File "main.py", line 106, in <module>
  File "main.py", line 70, in main_app
  File "configfile.py", line 34, in configure
  File "configfile.py", line 82, in _configure_encoders
KeyError: 'index'
[21344] Failed to execute script main

**Comment by SQLSammy** [comment]
When the tags case sensitive, then "index" and "Index" are different. Maybe soemthing you can check and only use "index".

**Comment by maartentamboer** [comment]
Yes, that appears to be the problem.

**Comment by reimuell** [comment]
Hello , yes that's the problem "Index" or "index" is different. Now it works, or the work begins to prgramm PFD and MFD .

Anyone has already programmed PDF/MFD with mobiflight events? Sometimes it's easier to copy then to start from scratch.
