### ISSUE TITLE
Button LEDs support

### ISSUE THREAD

**Issue by vicentezc** [maartentamboer/X-Touch-Mini-FS2020#54]
Hello,

I just got an X-Touch-Mini, so I am programming it based on the original samples provided and comments in other issues.
I am struggling with the button LEDs.

I am using MobiFlight, and I manually updated the events.txt file to add new vars. The variables are working fine, and I can see that in MSFS they are working as expected.
However, I cannot make the button LEDs work.

As an example, here are my MobiFlight vars for the APPR button:
`A32NX_AUTOPILOT_APPR_MODE_RELEASED#0 (>L:A32NX_AUTOPILOT_APPR_MODE)`
`A32NX_AUTOPILOT_APPR_MODE_PRESSED#1 (>L:A32NX_AUTOPILOT_APPR_MODE)`

And here is my code for the APPR button for the A32NX (in "buttons"):

    {
      "index": 15,
      "event_press": {
        "type": "condition",
        "event": [ "{% if data.get_global_variable('APPR_ACTIVE') == true %}",
					 "{{ data.trigger_event('MobiFlight.A32NX_AUTOPILOT_APPR_MODE_RELEASED', 1) }}",
					 "{{ data.set_global_variable('APPR_ACTIVE', false) }}",
					 "{{ data.set_button_led(15, 0) }}",
                   "{% else %}",
					 "{{ data.trigger_event('MobiFlight.A32NX_AUTOPILOT_APPR_MODE_PRESSED', 1) }}",
					 "{{ data.set_global_variable('APPR_ACTIVE', true) }}",
					 "{{ data.set_button_led(15, 1) }}",
                   "{% endif %}" ]
      }
    }

I tried everything: 
`"{{ data.set_button_led(15, 1) }}",`
`"{{ data.set_button_led(15, True) }}",`
`"{{ data.set_button_led(15, true) }}",`

And of course, I also used the simvar_led method:

    {
      "index": 15,
      "event_press": {
        "type": "condition",
        "event": [ "{% if data.get_global_variable('APPR_ACTIVE') == true %}",
					 "{{ data.trigger_event('MobiFlight.A32NX_AUTOPILOT_APPR_MODE_RELEASED', 1) }}",
					 "{{ data.set_global_variable('APPR_ACTIVE', false) }}",
                   "{% else %}",
					 "{{ data.trigger_event('MobiFlight.A32NX_AUTOPILOT_APPR_MODE_PRESSED', 1) }}",
					 "{{ data.set_global_variable('APPR_ACTIVE', true) }}",
                   "{% endif %}" ]
      }
	  "simvar_led": "MobiFlight.A32NX_AUTOPILOT_APPR_MODE"
    }

If you have any ideas, I would be grateful.
Cheers!

Vicente

**Comment by maartentamboer** [comment]
Can you try this:
```json
{
  "index": 15,
  "event_short_press": {
    "type": "condition",
    "event": [ "{% if data.get_global_variable('APPR_ACTIVE') == true %}",
				 "{{ data.trigger_event('MobiFlight.A32NX_AUTOPILOT_APPR_MODE_RELEASED', 1) }}",
				 "{{ data.set_global_variable('APPR_ACTIVE', False) }}",
				 "{{ data.set_button_led(15, False) }}",
               "{% else %}",
				 "{{ data.trigger_event('MobiFlight.A32NX_AUTOPILOT_APPR_MODE_PRESSED', 1) }}",
				 "{{ data.set_global_variable('APPR_ACTIVE', True) }}",
				 "{{ data.set_button_led(15, True) }}",
               "{% endif %}" ]
  }
}
```

**Comment by vicentezc** [comment]
Thanks for the answer.

So I copy pasted your suggestion (only modifying to upper case "True" instead of lower case "true" in the if statement and it works.
However, I had tried using:
`"{{ data.set_button_led(15, True) }}",`
`"{{ data.set_button_led(15, False) }}",`

(Both with lower case and upper case).

Really weird.
Anyway thanks a lot for the help!
Cheers!

Vicente
