### ISSUE TITLE
Set-Up Issue - 2

### ISSUE THREAD

**Issue by K3V1NSR** [maartentamboer/X-Touch-Mini-FS2020#59]
Hi Maarten,

I think I'm having the same issue as tombaer1044 before, but unfortunately that topic was closed due to inactivity.
I got myself a Mini today and was trying to get it working with the zip you provided.

I've set the encoders to the relative2 mode in the x-touch editor. Started FS2020 and got in the stock 747 to test it.

CMD says the following:
Midi input devices: ['X-TOUCH MINI 0']
Midi output devices: ['Microsoft GS Wavetable Synth 0', 'X-TOUCH MINI 1']
Using midi input device: X-TOUCH MINI 0
Using midi output device: X-TOUCH MINI 1
Current aircraft: b'Boeing 747-8i Asobo'
Loading config file: Configurations/config_default.json

But I cannot get the Mini to work in the plane. The lights on the console in the plane do work when I turn on A/P and change and set items as flight-level and heading.

Would you be able to advise what I could do or change in the setup to get it working?

Alvast bedankt!

Groeten Kevin

**Comment by maartentamboer** [comment]
When you press any buttons on the x-touch mini do you see any activity in the console output of the application?

**Comment by K3V1NSR** [comment]
Yes I do:

on_note_data BTN: 22
Layer Change to ActiveLayerIdentifier.B
on_note_data BTN: 22
on_note_data BTN: 20
on_note_data BTN: 20
on_note_data BTN: 30
on_note_data BTN: 30
on_note_data BTN: 19
on_note_data BTN: 19
on_note_data BTN: 31
on_note_data BTN: 31
on_note_data BTN: 27
on_note_data BTN: 27
on_note_data BTN: 23
on_note_data BTN: 23
on_note_data BTN: 3
Layer Change to ActiveLayerIdentifier.A
on_note_data BTN: 3
on_note_data BTN: 5
on_note_data BTN: 5
on_note_data BTN: 2
on_note_data BTN: 2
on_cc_data: 6: 65
on_cc_data: 6: 65
on_cc_data: 3: 63
on_cc_data: 5: 63
on_cc_data: 2: 65
on_cc_data: 2: 65
on_cc_data: 4: 65
on_cc_data: 6: 65
on_cc_data: 3: 63
on_cc_data: 3: 63
on_cc_data: 7: 63
on_cc_data: 7: 63
on_cc_data: 7: 63
on_cc_data: 2: 65
on_cc_data: 2: 65
on_cc_data: 2: 66
on_cc_data: 7: 63
on_cc_data: 1: 63
on_cc_data: 1: 63
on_cc_data: 8: 65
on_cc_data: 8: 65
on_cc_data: 3: 65
on_cc_data: 3: 65
on_cc_data: 6: 63
on_cc_data: 6: 63
on_cc_data: 6: 63
on_cc_data: 4: 63
on_cc_data: 4: 62
on_cc_data: 5: 65
on_cc_data: 5: 65
on_cc_data: 5: 65
on_note_data BTN: 11
on_note_data BTN: 11
on_note_data BTN: 13
on_note_data BTN: 13
on_note_data BTN: 12
on_note_data BTN: 12
on_note_data BTN: 6
on_note_data BTN: 2
on_note_data BTN: 6
on_note_data BTN: 2
on_note_data BTN: 15
on_note_data BTN: 15
on_note_data BTN: 16
on_note_data BTN: 9
on_note_data BTN: 16
on_note_data BTN: 9
on_note_data BTN: 11
on_note_data BTN: 7
on_note_data BTN: 11
on_note_data BTN: 7

**Comment by maartentamboer** [comment]
Can you try the TBM? That is my goto airplane for testing things. I have not flown the 747 with this

**Comment by K3V1NSR** [comment]
problem solved it seems. I had issues with the 747 and 320. Now flying the 787 and it works! thanks for your replies.
I just have to figure out the layout and label them accordingly on the X-Touch

**Comment by K3V1NSR** [comment]
Also figured that out now. I'll try to adjust some functions and add it in the config.
Hope it all works out well for more a comfortable sim experience. Bedankt voor je hulp zover :)
