### ISSUE TITLE
1.6.1 CRJ encoder 6: NAV1 same as encoder5: COM1

### ISSUE THREAD

**Issue by rostykk** [maartentamboer/X-Touch-Mini-FS2020#67]
![image](https://user-images.githubusercontent.com/3607571/114321512-6c665480-9b1b-11eb-9fb6-a7357eebcd80.png)

**Comment by elewarr** [comment]
Yes, it is intended - long press on given encoder activates COM for 5th encoder and NAV for 6th, then you can rotate it to select frequency. Short press switches between whole and fraction.
