### ISSUE TITLE
[Information] Mobiflight WASM module crashes since last World Update France

### ISSUE THREAD

**Issue by SQLSammy** [maartentamboer/X-Touch-Mini-FS2020#68]
Hi guys,

when using the mobiflight module MSFS will crash after the last world update.

It's not your fault, it's not Mobiflight fault, it's Microsoft fault, because every WASM module crashes
since world update.

Wait for next MSFS update

**Comment by elewarr** [comment]
The issue still exists but there is a development:
https://forums.flightsimulator.com/t/wasm-standalone-module-causing-ctd-on-launch-after-world-update-4-patch/390583/194

**Comment by SQLSammy** [comment]
The hotfix (1.15.8.0) is now live on both the Microsoft Store and Steam. Issues addressed:

    WASM stand alone modules used in some add-ons are no longer working
    Cockpit screens can be unresponsive if the RTC is not skipped

The launcher update is approximately 1 GB.

**Comment by SQLSammy** [comment]
First test: I can get MSFS with the mobiflight module into flight

**Comment by elewarr** [comment]
Works for me too, yay!
