### ISSUE TITLE
CRJ config use mobiflight - Rotary not smooth

### ISSUE THREAD

**Issue by moguay** [maartentamboer/X-Touch-Mini-FS2020#69]
Hi, Really good and waited for this update, but I find the use of rotary controls really not smooth and not practical during flights.

Any idea why ?

**Comment by maartentamboer** [comment]
You might be affected by the increment bug.

https://github.com/maartentamboer/X-Touch-Mini-FS2020/issues/32
https://forums.flightsimulator.com/t/heading-increment-bug-10-degree-instead-of-1-explained/290173

**Comment by maartentamboer** [comment]
WU4 should have fixed the increment bug https://forums.flightsimulator.com/t/heading-increment-bug-10-degree-instead-of-1-explained/290173/609
