### ISSUE TITLE
Last dev of A320NX uses local variables: it is possible to control them ?

### ISSUE THREAD

**Issue by JLD95** [maartentamboer/X-Touch-Mini-FS2020#70]
Hi,

with last dev of A320Nx, the spoiler logic is now custom so it can be realistic. That's the reason why the simvar SPOILERS_ARMED does not work anymore. For now, A320Nx uses local variables:
FCU stuff:
https://docs.flybywiresim.com/start/autopilot-fbw/

For other variables:
https://github.com/flybywiresim/a32nx/blob/master/docs/a320-simvars.md

it is possible to add them in X6TouchMini ?

**Comment by maartentamboer** [comment]
It might be possible by using the mobiflight mod
