### ISSUE TITLE
simvar_led's not working 

### ISSUE THREAD

**Issue by DrRajJena** [maartentamboer/X-Touch-Mini-FS2020#71]
Hi. I am trying to work out why Simvar LEDs have never worked correctly for me. 

Today I upgraded to 1.6.1 release, updated the x-touch mini config files using x-touch editor, and used the default config flying a TBM-930. 

As the x-touch-mini-fs2020 app starts I verified that it is using X-TOUCH MINI 1 as the midi output device.

Input commands from the x-touch mini (knob encoders, knob press and buttons) all work correctly.

I have tried sending midi commands to the x-touch to turn on and off LEDs from the Bome SendSx tool and I can get the LEDs to light up and turn off with MIDI commands so I know my x-touch LEDs are working

Any ideas why I am not getting any LED response at all on my x-touch?

**Comment by maartentamboer** [comment]
That's strange, did you make any changes in the x-touch editor in the buttons section? And can you let me know which commands you send with the SedSx tool?

**Comment by DrRajJena** [comment]
Thanks! When I use SendSx I read these codes on Midi In when I press button 1
9A 08 7F (press)
8A 08 00 (release)

So I send this code and button 1 LED illuminates
9A 08 7F

And I send this code and button1 LED goes out
8A 08 00

Reading from x-touch editor I following details:
GLOBAL TAB:
  Device ID 1,Global CH 2
  RXMidi control Button LEDs NOTE0-NOTE15
BUTTONS TAB looks like this...
  
![image](https://user-images.githubusercontent.com/69584758/119228260-15846f80-bb0a-11eb-94c7-9bda5f6cf53a.png)

![image](https://user-images.githubusercontent.com/69584758/119228320-5da39200-bb0a-11eb-91ea-4e9471be7b6f.png)

Is this all as it should be?

**Comment by dachande** [comment]
Same problem here although I'm using a BCR2000 instead of a X-Touch Mini. When the buttons are set up correctly I can control the corresponding switches in the sim and I also can send the note-on and note-off commands via MDI to the BCR2000 to control the leds, but when manually flipping a switch in the sim, the lights on the BCR2000 won't change.
It almost looks like the change in the simvar is not recognized by the software and converted into the corresponding MIDI command.

**Comment by cupax1000** [comment]
I have the exact same problem. Too bad, I'm missing this a lot to have a perfect MSFS controller.

**Comment by maartentamboer** [comment]
It might be your global midi channel: https://github.com/maartentamboer/X-Touch-Mini-FS2020/discussions/121#discussioncomment-3340869 

Feel free to reopen if needed
