### ISSUE TITLE
CRJ config missing FLC/speed function

### ISSUE THREAD

**Issue by Eraysor** [maartentamboer/X-Touch-Mini-FS2020#77]
The config for the Speed function is missing (supposed to be button 12).

I've tried to fix it myself but to no avail with the following:

In config_crj.json:

    {
      "index": 12,
      "event_press": { "event": "MobiFlight.ASCRJ_FCP_SPEED_BTN", "type": "manual", "value": 1 }
    },

In events.user.txt:

// 12. FLC
ASCRJ_FCP_SPEED_BTN#(L:ASCRJ_FCP_SPEED,Bool) ! (>L:ASCRJ_FCP_SPEED,Bool)

But this doesn't work.  I can't figure it out....

**Comment by maartentamboer** [comment]
I think that in the latest config this is tied to button 3 https://github.com/maartentamboer/X-Touch-Mini-FS2020/blob/main/Configurations/config_crj.json#L105-L107 

Feel free to reopen if not
