### ISSUE TITLE
"Automatic change to layer A" msg from app ? after pressing any layer B button - Thank You for great work.

### ISSUE THREAD

**Issue by supportaventura** [maartentamboer/X-Touch-Mini-FS2020#90]
All works great on layer A -- Switching to B is fine it will stay there , but after ANY encoder or button is changed it will go back to LAYER A - and console gives message : Automatic change to layer A -- Why ?- THANKS AGAIN !!!!

this happens if button is assigned or not.

**Comment by maartentamboer** [comment]
You can change this in the config file: https://github.com/maartentamboer/X-Touch-Mini-FS2020/blob/db1da3cc6b4c1dc86776c3219a73e5e2432942c1/Configurations/config.json#L35
