### ISSUE TITLE
Mobiflight events

### ISSUE THREAD

**Issue by reimuell** [maartentamboer/X-Touch-Mini-FS2020#94]
Is it possible to get information which Mobiflight events are supported, which one is the correct documentation.
All Mobiflight events are shown here: https://hubhop.mobiflight.com/#/
If I use eg "Mobiflight.AS3000_PFD_SOFTKEYS_1" a message is shown that this event is not supported otherwise it is working well.
This message is appearing because the event is not part of simconnect, correct?
The test of  suppported events should consider Mobiflight events.

If I look to the official Mobiflight documentation the name for this button should be:
AS3000_PFD_1_SOFTKEYS_1
Using this coding does not work.
Of course try an error is a possibility but not a convienient one.
All my test have been done with the latestet software release (Mobiflight and X-touch-mini-FS2020 using the default TBM930 from Asobo.
thx.

**Comment by Koseng** [comment]
In the community folder you need the mobiflight-event-module (the mobiflight WASM). There in modules\events.txt is the list of all events which are currently mapped.

All those events are useable.
