### ISSUE TITLE
Process hangs and can not be terminated

### ISSUE THREAD

**Issue by FreshDave29** [maartentamboer/X-Touch-Mini-FS2020#97]
If the program loses connection to the Midi-Controller, or the configuration.json is changed during runtime, the process will run forever without accepting any inputs.
It can not be terminated by the Windows Task Manager nor a taskkill command. A forced shutdown (powerbutton) of the PC is necessary in order to be able to restart X-Touch-Mini-FS2020.exe again.

**Comment by maartentamboer** [comment]
PR #100 from @Koseng merged and released as version 1.9.0

**Comment by Koseng** [comment]
Maybe do some testing with the new version. I am not sure whether it really fixes the problem. It's a try.
